---
title: "Portal yearly analysis"
author: "Renata Diaz"
date: "1/2/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(disturbancemete)
```

## Load data

```{r load data, echo = F}

portal_granivores <- load_rodent_data() # defaults to controls & power

head(portal_granivores)
```

## Split by year

```{r divide into annual communities}

portal_yearly_communities <- list()

for(i in 1:length(unique(portal_granivores$year))) {
  this_year <- unique(portal_granivores$year)[i]
  portal_yearly_communities[[i]] <- extract_portal_year(portal_granivores, chosen_year= this_year)
  names(portal_yearly_communities)[i]<-this_year
}

#portal_yearly_communities <- portal_yearly_communities[1:10]

```

## Get ps

```{r community ps, eval = F}

for(i in 1:10) {
  

get_probs <- function(year, list_of_communities) {
  dir.create(paste0('./sim_storage_yearly_100draws/', i, '/'))

thisone <- list_of_communities[[year]]
thispath <- paste0('./sim_storage_yearly_100draws/', i, '/', year)
dir.create(thispath)
probs <- get_community_prob(thisone, thispath, 100)

return(probs)
}

all_probs <- lapply(X = names(portal_yearly_communities), FUN = get_probs,
                    list_of_communities = portal_yearly_communities)
names(all_probs) <- names(portal_yearly_communities)
all_probs_df <- as.data.frame(names(portal_yearly_communities))
colnames(all_probs_df) <- 'year'
get_distp_from_list <- function(year, list_of_ps, dist_index) {
return(as.numeric(list_of_ps[[year]][dist_index]))
  }

all_probs_df$sad_p <- vapply(all_probs_df$year, FUN = get_distp_from_list,
                             list_of_ps = all_probs, dist_index = 1, FUN.VALUE = as.numeric(all_probs[[1]][1]))
all_probs_df$ipd_p <- vapply(all_probs_df$year, FUN = get_distp_from_list,
                             list_of_ps = all_probs, dist_index = 2, FUN.VALUE = as.numeric(all_probs[[1]][1]))

print(all_probs_df)

write.csv(all_probs_df, paste0('./sim_storage_yearly_100draws/', i, '/probs_df.csv'),  row.names= F)

}


```

```{r get ps from multiple sims}

add_ps <- function(it_index) {
  
  this_path <- paste0('sim_storage_yearly_100draws/', it_index, '/probs_df.csv')
  
  new_df <- read.csv(this_path)
  new_df$it_index <- it_index
  
  return(new_df)
}

ps_100draws <- add_ps(1)
for(i in 2:10) {
  ps_100draws <- rbind(ps_100draws, add_ps(i))
}

summary_100draws <- ps_100draws %>%
  dplyr::mutate(year = as.numeric(year)) %>%
  dplyr::group_by(year) %>%
  dplyr::summarize(sad_mean = mean(sad_p), 
                   ipd_mean = mean(ipd_p),
                   sad_2p5 = quantile(sad_p, probs = 0.025), 
                   sad_97p5 = quantile(sad_p, probs = 0.975),
                   ipd_2p5 = quantile(ipd_p, probs=0.025),
                   ipd_97p5 = quantile(ipd_p, probs = 0.975)) %>%
  dplyr::ungroup() 
```

```{r plots, echo = F}

cpt_years <- c(1984, 1992, 1999, 2009)

library(ggplot2)

probs_sad_plot <- ggplot(data = summary_100draws, aes(x = summary_100draws$year, y = summary_100draws$sad_mean)) +

  geom_errorbar(aes(x = summary_100draws$year,
                    ymax = summary_100draws$sad_97p5,
                    ymin = summary_100draws$sad_2p5), color = 'grey') +
    geom_point(aes(x = summary_100draws$year, y = summary_100draws$sad_mean), size = 2) + 
  geom_vline(xintercept = cpt_years, color = 'red') +
  theme_bw() + 
  labs(title = 'SAD p', x = 'Year', y = 'log p')

probs_sad_plot



probs_ipd_plot <- ggplot(data = summary_100draws, aes(x = summary_100draws$year, y = summary_100draws$ipd_mean)) +

  geom_errorbar(aes(x = summary_100draws$year,
                    ymax = summary_100draws$ipd_97p5,
                    ymin = summary_100draws$ipd_2p5), color = 'grey') +
    geom_point(aes(x = summary_100draws$year, y = summary_100draws$ipd_mean), size = 2) + 
    geom_vline(xintercept = cpt_years, color = 'red') +
  theme_bw() + 
  labs(title = 'IPD p', x = 'Year', y = 'log p')

probs_ipd_plot
```
